####################
## africa

ao: caf           # Angola
bj: caf           # Benin
bw: caf           # Botswana
bf: caf           # Burkina Faso
bi: caf           # Burundi
cv: caf           # Cape Verde
cf: caf           # Central African Republic
td: caf           # Chad
km: caf           # Comoros
cg: caf           # Congo
cd: caf           # Congo DR
dj: caf           # Djibouti
gq: caf           # Equatorial Guinea
er: caf           # Eritrea
et: caf           # Ethiopia
ga: caf           # Gabon
gm: caf           # Gambia
gn: caf           # Guinea
gw: caf           # Guinea-Bissau
ke: caf           # Kenya
ls: caf           # Lesotho
lr: caf           # Liberia
mg: caf           # Madagascar
mw: caf           # Malawi
ml: caf           # Mali
mr: caf           # Mauritania
mu: caf           # Mauritius
mz: caf           # Mozambique
na: caf           # Namibia
ne: caf           # Niger
rw: caf           # Rwanda
st: caf           # São Tomé and Príncipe
sn: caf           # Senegal
yc: caf           # Seychelles
sl: caf           # Sierra Leone
so: caf           # Somalia
ss: caf           # South Sudan
sd: caf           # Sudan
sz: caf           # Swaziland
tg: caf           # Togo
ug: caf           # Uganda
tz: caf           # Tanzania
zm: caf           # Zambia
zw: caf           # Zimbabwe
dz: caf           # Algeria
eg: caf           # Egypt
ma: caf           # Morocco
ly: caf           # Libya
tn: caf           # Tunisia
ci: caf           # Côte d'Ivoire
gh: caf           # Ghana
ng: caf           # Nigeria
cm: caf           # Cameroon
za: caf           # South Africa
