####################
## africa
##
## see http://en.wikipedia.org/wiki/List_of_FIFA_country_codes

ao: ANG           # Angola
bj: BEN           # Benin
bw: BOT           # Botswana
bf: BFA           # Burkina Faso
bi: BDI           # Burundi
cv: CPV           # Cape Verde
cf: CTA           # Central African Republic
td: CHA           # Chad
km: COM           # Comoros
cg: CGO           # Congo
cd: COD           # Congo DR
dj: DJI           # Djibouti
gq: EQG           # Equatorial Guinea
er: ERI           # Eritrea
et: ETH           # Ethiopia
ga: GAB           # Gabon
gm: GAM           # Gambia
gn: GUI           # Guinea
gw: GNB           # Guinea-Bissau
ke: KEN           # Kenya
ls: LES           # Lesotho
lr: LBR           # Liberia
mg: MAD           # Madagascar
mw: MWI           # Malawi
ml: MLI           # Mali
mr: MTN           # Mauritania
mu: MRI           # Mauritius
mz: MOZ           # Mozambique
na: NAM           # Namibia
ne: NIG           # Niger
rw: RWA           # Rwanda
st: STP           # São Tomé and Príncipe
sn: SEN           # Senegal
yc: SEY           # Seychelles
sl: SLE           # Sierra Leone
so: SOM           # Somalia
ss: SSD           # South Sudan
sd: SDN           # Sudan
sz: SWZ           # Swaziland
tg: TOG           # Togo
ug: UGA           # Uganda
tz: TAN           # Tanzania
zm: ZAM           # Zambia
zw: ZIM           # Zimbabwe
dz: ALG           # Algeria
eg: EGY           # Egypt
ma: MAR           # Morocco
ly: LBY           # Libya
tn: TUN           # Tunisia
ci: CIV           # Côte d'Ivoire
gh: GHA           # Ghana
ng: NGA           # Nigeria
cm: CMR           # Cameroon
za: RSA           # South Africa