####################
# africa country internet top level domains
#
# see en.wikipedia.org/wiki/List_of_Internet_top-level_domains


ao: ao           # Angola
bj: bj           # Benin
bw: bw           # Botswana
bf: bf           # Burkina Faso
bi: bi           # Burundi
cv: cv           # Cape Verde
cf: cf           # Central African Republic
td: td           # Chad
km: km           # Comoros
cg: cg           # Congo
cd: cd           # Congo DR
dj: dj           # Djibouti
gq: gq           # Equatorial Guinea
er: er           # Eritrea
et: et           # Ethiopia
ga: ga           # Gabon
gm: gm           # Gambia
gn: gn           # Guinea
gw: gw           # Guinea-Bissau
ke: ke           # Kenya
ls: ls           # Lesotho
lr: lr           # Liberia
mg: mg           # Madagascar
mw: mw           # Malawi
ml: ml           # Mali
mr: mr           # Mauritania
mu: mu           # Mauritius
mz: mz           # Mozambique
na: na           # Namibia
ne: ne           # Niger
rw: rw           # Rwanda
st: st           # São Tomé and Príncipe
sn: sn           # Senegal
sl: sl           # Sierra Leone
so: so           # Somalia
ss: ss           # South Sudan
sd: sd           # Sudan
sz: sz           # Swaziland
tg: tg           # Togo
ug: ug           # Uganda
tz: tz           # Tanzania
zm: zm           # Zambia
zw: zw           # Zimbabwe
dz: dz           # Algeria
eg: eg           # Egypt
ma: ma           # Morocco
ly: ly           # Libya
tn: tn           # Tunisia
ci: ci           # Côte d'Ivoire
gh: gh           # Ghana
ng: ng           # Nigeria
cm: cm           # Cameroon
za: za           # South Africa
  
###########
# NB: renamed - sc in use for scotland

yc: sc           # Seychelles


###############################
# dependencies & territories

yt: yt     # Mayotte (FR)
re: re     # Réunion (FR)
