####################
# africa

ao: AGO           # Angola
bj: BEN           # Benin
bw: BWA           # Botswana
bf: BFA           # Burkina Faso
bi: BDI           # Burundi
cv: CPV           # Cape Verde
cf: CAF           # Central African Republic
td: TCD           # Chad
km: COM           # Comoros
cg: COG           # Congo
cd: COD           # Congo DR
dj: DJI           # Djibouti
gq: GNQ           # Equatorial Guinea
er: ERI           # Eritrea
et: ETH           # Ethiopia
ga: GAB           # Gabon
gm: GMB           # Gambia
gn: GIN           # Guinea
gw: GNB           # Guinea-Bissau
ke: KEN           # Kenya
ls: LSO           # Lesotho
lr: LBR           # Liberia
mg: MDG           # Madagascar
mw: MWI           # Malawi
ml: MLI           # Mali
mr: MRT           # Mauritania
mu: MUS           # Mauritius
mz: MOZ           # Mozambique
na: NAM           # Namibia
ne: NER           # Niger
rw: RWA           # Rwanda
st: STP           # São Tomé and Príncipe
sn: SEN           # Senegal
yc: SYC           # Seychelles
sl: SLE           # Sierra Leone
so: SOM           # Somalia
ss: SSD           # South Sudan
sd: SDN           # Sudan
sz: SWZ           # Swaziland
tg: TGO           # Togo
ug: UGA           # Uganda
tz: TZA           # Tanzania
zm: ZMB           # Zambia
zw: ZWE           # Zimbabwe
dz: DZA           # Algeria
eg: EGY           # Egypt
ma: MAR           # Morocco
ly: LBY           # Libya
tn: TUN           # Tunisia
ci: CIV           # Côte d'Ivoire
gh: GHA           # Ghana
ng: NGA           # Nigeria
cm: CMR           # Cameroon
za: ZAF           # South Africa

###############################
# dependencies & territories

yt: MYT     # Mayotte (FR)
re: REU     # Réunion (FR)
